{{- if and .Values.rbac.create .Values.k8s.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aerospike-cluster-manager.fullname" . }}
  labels:
    {{- include "aerospike-cluster-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "aerospike-cluster-manager.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aerospike-cluster-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
