{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aerospike-cluster-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aerospike-cluster-manager.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "aerospike-cluster-manager.selectorLabels" . | nindent 6 }}
{{- end }}
