apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aerospike-admin-ui.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aerospike-admin-ui.labels" . | nindent 4 }}
data:
  CORS_ORIGINS: {{ .Values.env.corsOrigins | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  DATABASE_PATH: "/app/data/connections.db"
  K8S_MANAGEMENT_ENABLED: {{ .Values.k8s.enabled | quote }}
